dubbo:
  application:
    name: cls-service
    registry:
      address: zookeeper://192.168.144.155:2181
    protocol:
      port: -1
    consumer:
       check:false

#连接数据库
spring:
  datasource:
    url: jdbc:mysql://10.36.140.21:3306/db_cls?serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
