#配置dubbo的
dubbo:
  application:
    name: web-classes
  registry:
    address: zookeeper://192.168.144.155:2181
  consumer:
    #首次启动不检查提供者是否存在
    check: false
  protocol:
    port: -1

spring:
  datasource:
    url: jdbc:mysql://10.36.140.21/db_cls?serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver



