#配置dubbo的
server:
  port: 80
dubbo:
  application:
    name: web-manager
  registry:
    address: zookeeper://192.168.195.188:2181
  consumer:
    #首次启动不检查提供者是否存在
    check: false
spring:
  datasource:
    url: jdbc:mysql://db_cls?serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver




