dubbo:
  application:
    name: web-classes
  registry:
    address: zookeeper://192.168.144.155:2181
  consumer:
    check: false
  protocol:
    port: -1


spring:
  datasource:
    url: jdbc:mysql:///db_cls?serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver



